version: "3.9"

x-conf: &conf
  # 最新バージョンはここで確認すること
  # https://www.mongodb.com/try/download/community
  image: mongo:7.0.5
  # command: --keyFile /etc/replicaset.key --replSet rs0
  command: mongod --replSet rs0

services:
  mongodb:
    container_name: go_migrate_mongo_primary
    <<: *conf
    ports:
      - "27017:27017"
    volumes:
      # - ./replicaset.key:/etc/replicaset.key
      - go_migrate_mongo_primary_data:/data/db

  mongo-secondary:
    container_name: go_migrate_mongo_secondary
    <<: *conf
    ports:
      - "27018:27017"
    volumes:
      # - ./replicaset.key:/etc/replicaset.key
      - go_migrate_mongo_secondary_data:/data/db

  mongo-tertiary:
    container_name: go_migrate_mongo_tertiary
    <<: *conf
    ports:
      - "27019:27017"
    volumes:
      # - ./replicaset.key:/etc/replicaset.key
      - go_migrate_mongo_tertiary_data:/data/db

  mongo-:
    container_name: go_migrate_mongo_arbiter
    <<: *conf
    ports:
      - "27020:27017"
    volumes:
      # - ./replicaset.key:/etc/replicaset.key
      - go_migrate_mongo_arbiter_data:/data/db

  ## Docker上でhttps://github.com/golang-migrate/migrateを実行するためのコンテナ
  ## https://hub.docker.com/r/migrate/migrate
  migrate:
    image: migrate/migrate:latest
    entrypoint: sh
    tty: true
    volumes:
      - .:/var/task
    working_dir: /var/task
    command: ""

volumes:
  go_migrate_mongo_primary_data:
  go_migrate_mongo_secondary_data:
  go_migrate_mongo_tertiary_data:
  go_migrate_mongo_arbiter_data:
